DROP TABLE AEROPORT CASCADE CONSTRAINTS;

DROP TABLE BILLET CASCADE CONSTRAINTS;

DROP TABLE PROMOTION CASCADE CONSTRAINTS;

DROP TABLE EQUIPAGE CASCADE CONSTRAINTS;

DROP TABLE PASSAGER CASCADE CONSTRAINTS;

DROP TABLE EMPLOYE CASCADE CONSTRAINTS;

DROP TABLE CLIENT CASCADE CONSTRAINTS;

DROP TABLE AVION CASCADE CONSTRAINTS;

DROP TABLE CLASSE CASCADE CONSTRAINTS;

DROP TABLE TERMINAL CASCADE CONSTRAINTS;

DROP TABLE VOL_COMM CASCADE CONSTRAINTS;

DROP TABLE RESERVATION CASCADE CONSTRAINTS;

DROP TABLE PLACE CASCADE CONSTRAINTS;

DROP TABLE SPECIALITE CASCADE CONSTRAINTS;

DROP TABLE VOL_REEL CASCADE CONSTRAINTS;

DROP TABLE RECEVOIR CASCADE CONSTRAINTS;

DROP TABLE ASSIGNER_A CASCADE CONSTRAINTS;

DROP TABLE CONCERNER CASCADE CONSTRAINTS;
